################################################################################
################################################################################
###
###  This file is automatically generated. Do not change this file! Changes
###  will get overwritten! Change the source file for "setup.py" instead.
###  This is either 'packageinfo.json' or 'packageinfo.jsonc'
###
################################################################################
################################################################################


from setuptools import setup

def readme():
	with open("README.rst", "r", encoding="UTF-8-sig") as f:
		return f.read()

setup(
	author = "Jürgen Knauth",
	author_email = "pubsrc@binary-overflow.de",
	classifiers = [
		"Programming Language :: Python :: 3",
		"Development Status :: 3 - Alpha",
		"License :: OSI Approved :: Apache Software License",
	],
	description = "This python module provides an asynchroneous version of ping based on trio.",
	download_url = "https://github.com/jkpubsrc/......../tarball/0.2019.8.23",
	include_package_data = False,
	install_requires = [
		"trio",
	],
	keywords = [
		"trio",
		"ping",
	],
	license = "Apache 2.0",
	name = "jk_trioping",
	packages = [
		"jk_trioping",
	],
	url = "https://github.com/jkpubsrc/........",
	version = "0.2019.8.23",
	zip_safe = False,
	long_description = readme(),
)
